### ISSUE TITLE
Improve docs / debug error

### ISSUE THREAD

**Issue by gallettilance** [GiorgosKarantonis/Amazon-Movie-Reviews#1]
```
Traceback (most recent call last):
  File "preprocess.py", line 212, in <module>
    train_df = clean_data(train_df)
  File "preprocess.py", line 32, in clean_data
    df = df.loc[(df[['HelpfulnessNumerator', 'HelpfulnessDenominator', 'Score', 'Time']] >= 0).all(1)].apply(int)
  File "/home/lgallett/Documents/Amazon_Review/env/lib/python3.6/site-packages/pandas/core/frame.py", line 6913, in apply
    return op.get_result()
  File "/home/lgallett/Documents/Amazon_Review/env/lib/python3.6/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/home/lgallett/Documents/Amazon_Review/env/lib/python3.6/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/home/lgallett/Documents/Amazon_Review/env/lib/python3.6/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/home/lgallett/Documents/Amazon_Review/env/lib/python3.6/site-packages/pandas/core/series.py", line 131, in wrapper
    raise TypeError("cannot convert the series to " "{0}".format(str(converter)))
TypeError: ("cannot convert the series to <class 'int'>", 'occurred at index Id')
```

**Comment by GiorgosKarantonis** [comment]
I am trying to reproduce the error, but I don't get it... I basically followed the same steps we did together; downloaded the repo and pasted the datasets to the "Datasets" folder, opened sample.py and set fraq=1, then ran sample.py and finally ran preprocess.py. I had some issues with my previous computer and I had to replace it so now I am able to run the program (at least up to the "Adding Statistics" phase) 

As is shown in the logs, the error comes for this command: 

df = df.loc[(df[['HelpfulnessNumerator', 'HelpfulnessDenominator', 'Score', 'Time']] >= 0).all(1)].apply(int)

, which is basically a sanity check for these 4 features. The problem is that it encounters a missing value in one of these features and the apply() function cannot convert it to integer. The weird thing is that in my code the ".apply(int)" part of the command is not present, which I believe is the reason why I'm not getting the error... 

For now, I have left the program running to see if it's going to get stuck at some other point. If you want and have the time we could also set another meeting too or meet on Monday after class, to make sure that it's actually running without any changes in the original code.

**Comment by gallettilance** [comment]
What's your python version?

**Comment by gallettilance** [comment]
I will remove the `.apply(int)` part and see what happens

**Comment by GiorgosKarantonis** [comment]
It's Python 3.7.5
